---
- name: Download amdgpu-install package
  get_url:
    url: https://repo.radeon.com/amdgpu-install/7.2.3/ubuntu/noble/amdgpu-install_7.2.3.70203-1_all.deb
    dest: /tmp/amdgpu-install_7.2.3.70203-1_all.deb
    mode: "0644"

- name: Install amdgpu-install package
  apt:
    deb: /tmp/amdgpu-install_7.2.3.70203-1_all.deb
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Get kernel version
  shell: uname -r
  register: kernel_version
  changed_when: false

- name: Install linux headers and modules for current kernel
  apt:
    name:
      - "linux-headers-{{ kernel_version.stdout }}"
      - "linux-modules-extra-{{ kernel_version.stdout }}"
    state: present
  become: true

- name: Install amdgpu-dkms
  apt:
    name: amdgpu-dkms
    state: present
  become: true

- name: Create llm directory if it doesn't exist
  file:
    path: "{{ app_path }}/llm"
    state: directory

- name: Copy compose template
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/llm/{{ item | replace('.j2', '') }}"
    mode: "0644"
  register: config
  loop:
    - compose.yaml.j2
    - .env.j2

- name: Stop Ollama if config changed
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/llm"
    state: absent
  when: config.changed

- name: Start Ollama
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/llm"
    state: present
