---
# Docker registry

- name: Create /registry
  file:
    path: "{{ app_path }}/registry"
    state: directory
  register: registry_folder

- name: Copy template files to /registry
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/registry/{{ item | replace('.template', '') }}"
    mode: "0644"
  loop:
    - compose.yaml
    - config.yml
    - .env.template
  register: registry_config

- name: Run authentification setup
  ansible.builtin.script:
    chdir: "{{ app_path }}/registry"
    cmd: files/setup.sh
  when: registry_folder.changed

- name: Stop registry stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/registry"
    state: absent
  when: registry_config.changed

- name: Start registry stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/registry"
    state: present
