---
- name: Create traefik directory if it doesn't exist
  file:
    path: "{{ app_path }}/traefik"
    state: directory

- name: Copy traefik template files to traefik
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/traefik/{{ item | replace('.j2', '') }}"
    mode: "0644"
  loop:
    - compose.yaml
    - traefik.j2
    - .env.j2
  register: traefik_config

- name: Stop Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/traefik"
    state: absent
  when: traefik_config.changed

- name: Start Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/traefik"
    state: present
