---
- name: Create /srv/nextcloud
  file:
    path: /{{ app_path }}/nextcloud
    state: directory

- name: Get traefik_net network
  docker_network_info:
    name: traefik_net
  register: traefik_net_info

- name: subnet of traefik_net network
  ansible.builtin.set_fact:
    traefik_net_subnet: "{{(traefik_net_info.network.IPAM.Config[0].Subnet)}}"

- name: Copy nextcloud template files to /srv/nextcloud
  template:
    src: "{{ item }}"
    dest: /srv/nextcloud/{{ item | replace('.template', '') }}
    mode: "0644"
  loop:
    - docker-compose.yml
    - .env.template
  register: nextcloud_config

- name: Stop nextcloud
  community.docker.docker_compose_v2:
    project_src: /srv/nextcloud
    state: absent
  when: nextcloud_config.changed

- name: Start nextcloud
  community.docker.docker_compose_v2:
    project_src: /srv/nextcloud
    state: present

- name: Add Nextcloud Cron job
  ansible.builtin.cron:
    name: Nextcloud jobs
    hour: 2
    minute: 13
    job: docker compose -f {{app_path}}/nextcloud/docker-compose.yml exec -u www-data app php cron.php
