- name: Create docker data directory
  file:
    path: "{{ space_path }}/docker"
    state: directory
    mode: "0710"
  become: true

- name: Configure Docker daemon to use custom data directory
  copy:
    content: |
      {
        "data-root": "{{ space_path }}/docker"
      }
    dest: /etc/docker/daemon.json
    mode: "0644"
  become: true
  register: docker_config_changed

- name: Create containerd data directory
  file:
    path: "{{ space_path }}/containerd"
    state: directory
    mode: "0710"
  become: true

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml.bkp
  become: true

- name: Update containerd root path in config
  shell: |
    sed -i "s|root = '[^']*'|root = '{{ space_path }}/containerd'|" /etc/containerd/config.toml
  become: true
  register: containerd_config_changed

- name: Restart containerd daemon
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
  become: true

- name: Restart Docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  become: true
  when: docker_config_changed.changed
