---
- name: Create dolibarr path
  file:
    path: "{{ app_path }}/{{ tenant }}/dolibarr"
    state: directory
    mode: "0775"

- name: Copy template files to dolibarr
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/{{ tenant }}/dolibarr/{{ item | replace('.template', '') | replace('.jinja', '') }}"
    mode: "0644"
  loop:
    - compose.yaml
    - .env.template
  register: dolibarr_config

- name: Stop stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/{{ tenant }}/dolibarr"
    state: absent
  when: dolibarr_config.changed

- name: Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/{{ tenant }}/dolibarr"
    state: present
