---
# Use Caddy to serve files

- name: Create /srv/static-files
  file:
    path: /{{ app_path }}/static-files/served
    state: directory
  register: static_files_folder

- name: Create /srv/static-files/served
  file:
    path: /{{ app_path }}/static-files/served
    state: directory
    owner: "{{ linux_user }}"
  register: static_files_folder

- name: Copy template files to /srv/static-files
  template:
    src: "{{ item }}"
    dest: /srv/static-files/{{ item | replace('.template', '') }}
    mode: "0644"
  loop:
    - docker-compose.yml
    - .env.template
  register: static_files_config

- name: Stop stack
  community.docker.docker_compose_v2:
    project_src: /srv/static-files
    state: absent
  when: static_files_config.changed

- name: Start stack
  community.docker.docker_compose_v2:
    project_src: /srv/static-files
    state: present
