services:
  moodle:
    image: ad2ien/moodle:v5.1.3
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - moodle_data:/var/www/moodledata
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.moodle.rule=Host(`{{moodle_domain}}.${DOMAIN}`)"
      - "traefik.http.routers.moodle.entrypoints=websecure"
      - "traefik.http.services.moodle.loadbalancer.server.port=80"
      - "traefik.http.routers.moodle.tls.certresolver=letsencrypt"
    networks:
      - traefik
      - internal

  db:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    volumes:
      - db:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal

volumes:
  db:
  moodle_data:

networks:
  internal:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
