---
- name: Set SSH key filename
  ansible.builtin.set_fact:
    autossh_ssh_key_file: "{{ device_name }}-{{ device_master }}"

- name: Check if SSH key exists
  ansible.builtin.stat:
    path: /home/{{ linux_user }}/.ssh/{{ autossh_ssh_key_file }}
  register: ssh_key_stat

- name: Generate SSH key if not exists
  community.crypto.openssh_keypair:
    path: /home/{{ linux_user }}/.ssh/{{ autossh_ssh_key_file }}
    type: ed25519
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    mode: "0600"
    comment: "{{ autossh_ssh_key_file }}"
  when: not ssh_key_stat.stat.exists
  register: new_key

- name: Add public key to master authorized_keys
  ansible.posix.authorized_key:
    user: "{{ master_linux_user }}"
    key: "{{ new_key.public_key }}"
    state: present
  delegate_to: "{{ groups['master'][0] }}"
  when: new_key.changed

- name: Install autossh
  ansible.builtin.apt:
    name: autossh
    state: present
    update_cache: yes
  become: true

- name: Create systemd service directory for autossh-tunnel
  ansible.builtin.file:
    path: /etc/systemd/system/autossh-tunnel.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create autossh-tunnel systemd service
  ansible.builtin.template:
    src: autossh-tunnel.service.j2
    dest: /etc/systemd/system/autossh-tunnel.service
    owner: root
    group: root
    mode: "0644"
  become: true
  register: autossh_service

- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
  when: autossh_service.changed

- name: Enable and start autossh-tunnel service
  ansible.builtin.systemd_service:
    name: autossh-tunnel
    enabled: true
    state: started
  become: true

- name: Display autossh-tunnel service status
  ansible.builtin.command: systemctl status autossh-tunnel --no-pager
  register: autossh_status
  become: true

- name: Show autossh-tunnel service status
  ansible.builtin.debug:
    msg: "{{ autossh_status.stdout_lines }}"
