---
- name: Check if SSH key exists
  stat:
    path: /home/{{ linux_user }}/{{ autossh_ssh_key_path }}
  register: ssh_key_stat


- name: Generate SSH key if not exists
  openssh_keypair:
    path: /home/{{ linux_user }}/{{ autossh_ssh_key_path }}
    type: ed25519
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
    mode: "0600"
  when: not ssh_key_stat.stat.exists
  register: new_key

- name: Add public key to master authorized_keys
  authorized_key:
    user: "{{ master_linux_user }}"
    key: "{{ public_key.content | b64decode }}"
    state: present
  delegate_to: "{{ groups['master'][0] }}"

- name: Install autossh
  apt:
    name: autossh
    state: present
    update_cache: yes
  become: true

- name: Create systemd service directory for autossh-tunnel
  file:
    path: /etc/systemd/system/autossh-tunnel.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create autossh-tunnel systemd service
  template:
    src: autossh-tunnel.service.j2
    dest: /etc/systemd/system/autossh-tunnel.service
    owner: root
    group: root
    mode: "0644"
  become: true
  register: autossh_service

- name: Reload systemd daemon
  systemd_service:
    daemon_reload: true
  become: true
  when: autossh_service.changed

- name: Enable and start autossh-tunnel service
  systemd_service:
    name: autossh-tunnel
    enabled: true
    state: started
  become: true

- name: Display autossh-tunnel service status
  command: systemctl status autossh-tunnel --no-pager
  register: autossh_status
  become: true

- name: Show autossh-tunnel service status
  debug:
    msg: "{{ autossh_status.stdout_lines }}"
