---
- name: Create messaging
  file:
    path: "{{ app_path }}/messaging"
    state: directory

- name: Copy template files to messaging
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/messaging/{{ item | replace('.j2', '') }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
  loop:
    - compose.yaml.j2
    - element-config.json
  register: messaging_config

- name: Stop messaging stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/messaging"
    state: absent
  when: messaging_config.changed

- name: Start messaging stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/messaging"
    state: present
