---
- name: Create messaging
  file:
    path: "{{ app_path }}/messaging"
    state: directory

- name: Copy template files to messaging
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/messaging/{{ item | replace('.j2', '') }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
  loop:
    - compose.yaml.j2
    - element-config.json
    - hook-config.yml.j2
    - registration.yml.j2
  register: messaging_config

- name: Generate passkey
  command: >
    openssl genpkey -algorithm RSA -out {{ app_path }}/messaging/passkey.pem
    -pkeyopt rsa_keygen_bits:2048
  args:
    creates: "{{ app_path }}/messaging/passkey.pem"

- name: Stop stack if config changed
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/messaging"
    state: absent
  when: messaging_config.changed

- name: Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/messaging"
    state: present

- name: Read registration file
  slurp:
    src: "{{ app_path }}/messaging/registration.yml"
  register: registration_file

- name: Instructions to register Hookshot
  debug:
    msg:
      - "Send this in your Matrix admin room ({{ messaging_sub_domain }}.{{ domain }}):"
      - ""
      - "!admin appservices register"
      - "```"
      - "{{ registration_file.content | b64decode }}"
      - "```"
