---
- name: Create paheko path
  file:
    path: "{{ app_path }}/{{ tenant }}/paheko"
    state: directory
    mode: "0775"

- name: Copy template files to paheko
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/{{ tenant }}/paheko/{{ item | replace('.j2', '') }}"
    mode: "0644"
  loop:
    - compose.yaml.j2
    - config.local.php.j2
    - php.ini
  register: paheko_config

- name: Stop stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/{{ tenant }}/paheko"
    state: absent
  when: paheko_config.changed

- name: Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/{{ tenant }}/paheko"
    state: present
