---
- name: Update and upgrade packages
  apt:
    name: "*"
    state: latest

- name: debug display inventory_hostname
  ansible.builtin.debug:
    msg: System {{ inventory_hostname }}

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - {key: "PermitRootLogin", value: "no"}
    - {key: "PasswordAuthentication", value: "no"}
    - {key: "X11Forwarding", value: "no"}
    - {key: "PermitEmptyPasswords", value: "no"}
  notify:
    - restart sshd

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow

- name: Fail2ban
  apt:
    name: "fail2ban"
    state: latest
