services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:1.0.20210914-r4-ls52
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=$WIREGUARD_URL
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`{{wireguard_sub_domain}}.$DOMAIN`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.services.wireguard.loadbalancer.server.port=943"
      - "traefik.http.routers.wireguard.tls=true"
      - "traefik.http.routers.wireguard.tls.certresolver=letsencrypt"

networks:
  default:
    external: true
    name: ${TRAEFIK_NETWORK}
