---
- name: Create monitoring
  file:
    path: "{{ app_path }}/monitoring"
    state: directory

- name: Copy monitoring template files to monitoring
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/monitoring/{{ item | replace('.j2', '') }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
  loop:
    - compose.yaml.j2
    - grafana.ini
    - loki-config.yml
    - prometheus.yml
    - alertmanager.yml
    - alerts.yml
    - .env.j2
    - provisioning/datasources/datasource.yml
  register: monitoring_config

- name: Copy alloy config to monitoring
  copy:
    src: alloy-config.alloy
    dest: "{{ app_path }}/monitoring/alloy-config.alloy"
    owner: "{{ ansible_user }}"
    mode: "0644"

- name: Stop monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/monitoring"
    state: absent
  when: monitoring_config.changed

- name: Start monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/monitoring"
    state: present
