services:
  mediamtx:
    image: bluenviron/mediamtx:1.11.3
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./certs:/certs
    ports:
      - 1935:1935/tcp
      - 1936:1936/tcp
