x-dolibarr: &dolibarr
  image: dolibarr/dolibarr:16.0.5
  volumes:
    - custom:/var/www/html/custom
    - documents:/var/www/documents
  env_file: .env
  restart: unless-stopped

services:
  mariadb:
    image: mariadb:12.2-ubi
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  web:
    <<: *dolibarr
    environment:
      DOLI_CRON: 0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dolibarr.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.dolibarr.entrypoints=websecure"
      - "traefik.http.services.dolibarr.loadbalancer.server.port=80"
      - "traefik.http.routers.dolibarr.tls.certresolver=letsencrypt"

  cron:
    <<: *dolibarr
    environment:
      DOLI_CRON: 1
      DOLI_CRON_KEY: ${DOLI_CRON_KEY}

volumes:
  documents:
  custom:
  db:

networks:
  default:
    external: true
    name: ${TRAEFIK_NETWORK}
