---
- name: Install and configure VPS
  hosts: private_network_node
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/private.yml
  roles:
    - role: 00_basic-install
      tags: basic
    - role: private-node/000_autossh
      tags: autossh
    - role: private-node/00_relocate-docker
      tags: relocate-docker
    - role: private-node/01_traefik
      tags: traefik
    - role: private-node/04_video-server
      tags: video
    - role: private-node/05_cam
      tags: cam
    - role: 08_registry
      tags: registry
    - role: private-node/99_whoami
      tags: whoami
