---
# Deploy a notification tool https://github.com/ad2ien/help-the-stars/

- name: Create help-the-stars
  file:
    path: "{{ app_path }}/help-the-stars"
    state: directory

- name: Copy template files to help-the-stars
  template:
    src: "{{ item }}"
    dest: "{{ app_path }}/help-the-stars/{{ item | replace('.j2', '') }}"
    mode: "0644"
  loop:
    - compose.yaml
    - .env.j2
  register: help_the_stars_config

- name: Stop stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/help-the-stars"
    state: absent
  when: help_the_stars_config.changed

- name: Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}/help-the-stars"
    state: present
